name: animal_hospital
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  dio: ^5.3.3
  go_router: ^11.0.0
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.3
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/facebook_back.svg
    - assets/google_back.svg
    - assets/facebook_icon.svg
    - assets/google_icon.svg
    - assets/kakao.svg
    - assets/Ellipse5.png
    - assets/dogcard01.jpg
    - assets/dogcard02.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Swagger TTF
      fonts:
        - asset: assets/fonts/SDSwaggerTTF.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700